# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
gem:              [jekyll-paginate jekyll-gist]

# Setup
title:            Aditya Sathish
tagline:          'The internet home of Aditya Sathish'
description:      'A personal website (and sometimes blog) of one Aditya Sathish'
url:              http://adityasathis.github.io/
baseurl:          http://adityasathis.github.io/

author:
  name:           'Aditya Sathish'
  url:            http://adityasathis.github.io/
  baseurl:        http://adityasathis.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:		  [jekyll-paginate, jekyll-gist]
