# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
gem:              [jekyll-paginate jekyll-gist]

# Setup
title:            Aditya Sathish
tagline:          ''
description:      ''
url:              http://adityasathis.github.io/
baseurl:          '/'

paginate:         2
paginate_path:    "/blog/page-:num/"

# Custom vars
version:          1.1

port:             4001

github:
  repo:           https://github.com/poole/hyde

plugins:		  [jekyll-paginate, jekyll-gist]
